/* SPDX-License-Identifier: GPL-3.0-only */
/* Generated by tools/gen_scales.py; edit assets/scales/catalog.json. */
#pragma once
#define SCALE_LEGACY 16u
#define SCALE_TOTAL 70u
static const char *const N_SCALE[] = {"CHR", "MAJ", "MIN", "DOR", "MIX", "PEN", "MPEN", "HARM", "PHRY", "LYD", "LOC", "MEL", "BLUES", "WHOLE", "DIMHW", "DIMWH", "5EDO", "7EDO", "9EDO", "10EDO", "13EDO", "14EDO", "15EDO", "16EDO", "17EDO", "18EDO", "19EDO", "20EDO", "21EDO", "22EDO", "23EDO", "24EDO", "26EDO", "27EDO", "29EDO", "31EDO", "34EDO", "36EDO", "41EDO", "53EDO", "JI-MAJ", "JI-MIN", "JI-12", "JI-7L", "JI-7", "HARM8", "HARM16", "PARTCH", "HARRIS", "PYTH", "MT-1/4", "MT-1/3", "MT-1/6", "WERCK3", "KIRN3", "VALLOT", "YOUNG2", "RAST-J", "SABA-J", "SHRUTI", "SLENDR", "PELOG", "BP-ET", "BP-JI", "RAST", "BAYATI", "HIJAZ", "SABA", "HUSAYN", "SIKAH"};
static const char *const SCALE_TITLE[] = {"Chromatic", "Major", "Natural minor", "Dorian", "Mixolydian", "Major pentatonic", "Minor pentatonic", "Harmonic minor", "Phrygian", "Lydian", "Locrian", "Melodic minor", "Blues", "Whole tone", "Half-whole diminished", "Whole-half diminished", "5-tone equal division", "7-tone equal division", "9-tone equal division", "10-tone equal division", "13-tone equal division", "14-tone equal division", "15-tone equal division", "16-tone equal division", "17-tone equal division", "18-tone equal division", "19-tone equal division", "20-tone equal division", "21-tone equal division", "22-tone equal division", "23-tone equal division", "24-tone equal division", "26-tone equal division", "27-tone equal division", "29-tone equal division", "31-tone equal division", "34-tone equal division", "36-tone equal division", "41-tone equal division", "53-tone equal division", "Just major", "Just minor", "Just chromatic", "7-limit chromatic", "Just diatonic", "Harmonic series 8", "Harmonic series 16", "Partch 43-tone", "Harrison 8-tone", "Pythagorean", "Quarter-comma meantone", "Third-comma meantone", "Sixth-comma meantone", "Werckmeister III", "Kirnberger III", "Vallotti", "Young II", "Rast 11-limit", "Saba just", "Indian 22 shruti", "Slendro average", "Pelog", "Bohlen-Pierce equal", "Bohlen-Pierce just", "Rast", "Bayati", "Hijaz", "Saba", "Husayni", "Sikah"};
static const uint8_t SCALE_DEGREES[] = {12, 7, 7, 7, 7, 5, 5, 7, 7, 7, 7, 7, 6, 6, 8, 8, 5, 7, 9, 10, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26, 27, 29, 31, 34, 36, 41, 53, 7, 7, 12, 12, 7, 8, 16, 43, 8, 12, 12, 12, 12, 12, 12, 12, 12, 7, 8, 22, 5, 7, 13, 13, 7, 7, 7, 7, 7, 7};
static const uint8_t SCALE_FAMILY[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 7, 7, 7, 7, 7, 7};
#define SCALE_FAMILIES 8u
static const char *const SCALE_FAMILY_SHORT[] = {"ALL", "WEST", "EDO", "JUST", "HARM", "HIST", "WORLD", "BP", "MAQAM", "FAV"};
static const char *const SCALE_FAMILY_TITLE[] = {"All scales", "Western", "Equal divisions", "Just intonation", "Harmonic", "Historical", "Regional", "Non-octave", "Maqam models", "Favorites"};
typedef struct { uint8_t count; const int32_t *pitch; } micro_scale_t;
static const uint16_t SCALE_MASK[] = {0xfff, 0xab5, 0x5ad, 0x6ad, 0x6b5, 0x295, 0x4a9, 0x9ad, 0x5ab, 0xad5, 0x56b, 0xaad, 0x4e9, 0x555, 0x6db, 0xb6d};
static const int32_t SCALE_P16[] = {0, 24000, 48000, 72000, 96000, 120000};
static const int32_t SCALE_P17[] = {0, 17143, 34286, 51429, 68571, 85714, 102857, 120000};
static const int32_t SCALE_P18[] = {0, 13333, 26667, 40000, 53333, 66667, 80000, 93333, 106667, 120000};
static const int32_t SCALE_P19[] = {0, 12000, 24000, 36000, 48000, 60000, 72000, 84000, 96000, 108000, 120000};
static const int32_t SCALE_P20[] = {0, 9231, 18462, 27692, 36923, 46154, 55385, 64615, 73846, 83077, 92308, 101538, 110769, 120000};
static const int32_t SCALE_P21[] = {0, 8571, 17143, 25714, 34286, 42857, 51429, 60000, 68571, 77143, 85714, 94286, 102857, 111429, 120000};
static const int32_t SCALE_P22[] = {0, 8000, 16000, 24000, 32000, 40000, 48000, 56000, 64000, 72000, 80000, 88000, 96000, 104000, 112000, 120000};
static const int32_t SCALE_P23[] = {0, 7500, 15000, 22500, 30000, 37500, 45000, 52500, 60000, 67500, 75000, 82500, 90000, 97500, 105000, 112500, 120000};
static const int32_t SCALE_P24[] = {0, 7059, 14118, 21176, 28235, 35294, 42353, 49412, 56471, 63529, 70588, 77647, 84706, 91765, 98824, 105882, 112941, 120000};
static const int32_t SCALE_P25[] = {0, 6667, 13333, 20000, 26667, 33333, 40000, 46667, 53333, 60000, 66667, 73333, 80000, 86667, 93333, 100000, 106667, 113333, 120000};
static const int32_t SCALE_P26[] = {0, 6316, 12632, 18947, 25263, 31579, 37895, 44211, 50526, 56842, 63158, 69474, 75789, 82105, 88421, 94737, 101053, 107368, 113684, 120000};
static const int32_t SCALE_P27[] = {0, 6000, 12000, 18000, 24000, 30000, 36000, 42000, 48000, 54000, 60000, 66000, 72000, 78000, 84000, 90000, 96000, 102000, 108000, 114000, 120000};
static const int32_t SCALE_P28[] = {0, 5714, 11429, 17143, 22857, 28571, 34286, 40000, 45714, 51429, 57143, 62857, 68571, 74286, 80000, 85714, 91429, 97143, 102857, 108571, 114286, 120000};
static const int32_t SCALE_P29[] = {0, 5455, 10909, 16364, 21818, 27273, 32727, 38182, 43636, 49091, 54545, 60000, 65455, 70909, 76364, 81818, 87273, 92727, 98182, 103636, 109091, 114545, 120000};
static const int32_t SCALE_P30[] = {0, 5217, 10435, 15652, 20870, 26087, 31304, 36522, 41739, 46957, 52174, 57391, 62609, 67826, 73043, 78261, 83478, 88696, 93913, 99130, 104348, 109565, 114783, 120000};
static const int32_t SCALE_P31[] = {0, 5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000, 55000, 60000, 65000, 70000, 75000, 80000, 85000, 90000, 95000, 100000, 105000, 110000, 115000, 120000};
static const int32_t SCALE_P32[] = {0, 4615, 9231, 13846, 18462, 23077, 27692, 32308, 36923, 41538, 46154, 50769, 55385, 60000, 64615, 69231, 73846, 78462, 83077, 87692, 92308, 96923, 101538, 106154, 110769, 115385, 120000};
static const int32_t SCALE_P33[] = {0, 4444, 8889, 13333, 17778, 22222, 26667, 31111, 35556, 40000, 44444, 48889, 53333, 57778, 62222, 66667, 71111, 75556, 80000, 84444, 88889, 93333, 97778, 102222, 106667, 111111, 115556, 120000};
static const int32_t SCALE_P34[] = {0, 4138, 8276, 12414, 16552, 20690, 24828, 28966, 33103, 37241, 41379, 45517, 49655, 53793, 57931, 62069, 66207, 70345, 74483, 78621, 82759, 86897, 91034, 95172, 99310, 103448, 107586, 111724, 115862, 120000};
static const int32_t SCALE_P35[] = {0, 3871, 7742, 11613, 15484, 19355, 23226, 27097, 30968, 34839, 38710, 42581, 46452, 50323, 54194, 58065, 61935, 65806, 69677, 73548, 77419, 81290, 85161, 89032, 92903, 96774, 100645, 104516, 108387, 112258, 116129, 120000};
static const int32_t SCALE_P36[] = {0, 3529, 7059, 10588, 14118, 17647, 21176, 24706, 28235, 31765, 35294, 38824, 42353, 45882, 49412, 52941, 56471, 60000, 63529, 67059, 70588, 74118, 77647, 81176, 84706, 88235, 91765, 95294, 98824, 102353, 105882, 109412, 112941, 116471, 120000};
static const int32_t SCALE_P37[] = {0, 3333, 6667, 10000, 13333, 16667, 20000, 23333, 26667, 30000, 33333, 36667, 40000, 43333, 46667, 50000, 53333, 56667, 60000, 63333, 66667, 70000, 73333, 76667, 80000, 83333, 86667, 90000, 93333, 96667, 100000, 103333, 106667, 110000, 113333, 116667, 120000};
static const int32_t SCALE_P38[] = {0, 2927, 5854, 8780, 11707, 14634, 17561, 20488, 23415, 26341, 29268, 32195, 35122, 38049, 40976, 43902, 46829, 49756, 52683, 55610, 58537, 61463, 64390, 67317, 70244, 73171, 76098, 79024, 81951, 84878, 87805, 90732, 93659, 96585, 99512, 102439, 105366, 108293, 111220, 114146, 117073, 120000};
static const int32_t SCALE_P39[] = {0, 2264, 4528, 6792, 9057, 11321, 13585, 15849, 18113, 20377, 22642, 24906, 27170, 29434, 31698, 33962, 36226, 38491, 40755, 43019, 45283, 47547, 49811, 52075, 54340, 56604, 58868, 61132, 63396, 65660, 67925, 70189, 72453, 74717, 76981, 79245, 81509, 83774, 86038, 88302, 90566, 92830, 95094, 97358, 99623, 101887, 104151, 106415, 108679, 110943, 113208, 115472, 117736, 120000};
static const int32_t SCALE_P40[] = {0, 20391, 38631, 49804, 70196, 88436, 108827, 120000};
static const int32_t SCALE_P41[] = {0, 18240, 31564, 49804, 70196, 88436, 101760, 120000};
static const int32_t SCALE_P42[] = {0, 11173, 20391, 31564, 38631, 49804, 58251, 70196, 81369, 88436, 101760, 108827, 120000};
static const int32_t SCALE_P43[] = {0, 11173, 20391, 26687, 38631, 49804, 58251, 70196, 81369, 93313, 96883, 108827, 120000};
static const int32_t SCALE_P44[] = {0, 18240, 34291, 49804, 70196, 85709, 101760, 120000};
static const int32_t SCALE_P45[] = {0, 20391, 38631, 55132, 70196, 84053, 96883, 108827, 120000};
static const int32_t SCALE_P46[] = {0, 10496, 20391, 29751, 38631, 47078, 55132, 62827, 70196, 77263, 84053, 90587, 96883, 102958, 108827, 114504, 120000};
static const int32_t SCALE_P47[] = {0, 2151, 5327, 8447, 11173, 15064, 16500, 18240, 20391, 23117, 26687, 29413, 31564, 34741, 38631, 41751, 43508, 47078, 49804, 51955, 55132, 58251, 61749, 64868, 68045, 70196, 72922, 76492, 78249, 81369, 85259, 88436, 90587, 93313, 96883, 99609, 101760, 103500, 104936, 108827, 111553, 114673, 117849, 120000};
static const int32_t SCALE_P48[] = {0, 11173, 31564, 38631, 59022, 70196, 88436, 99609, 120000};
static const int32_t SCALE_P49[] = {0, 11369, 20391, 29413, 40782, 49804, 61173, 70196, 81564, 90587, 99609, 110978, 120000};
static const int32_t SCALE_P50[] = {0, 7605, 19316, 31026, 38631, 50342, 57947, 69658, 77263, 88974, 100684, 108289, 120000};
static const int32_t SCALE_P51[] = {0, 6350, 18957, 31564, 37914, 50521, 56872, 69479, 75829, 88436, 101043, 107393, 120000};
static const int32_t SCALE_P52[] = {0, 8859, 19674, 30489, 39348, 50163, 59022, 69837, 78696, 89511, 100326, 109185, 120000};
static const int32_t SCALE_P53[] = {0, 9022, 19218, 29413, 39022, 49804, 58827, 69609, 79218, 88827, 99609, 109218, 120000};
static const int32_t SCALE_P54[] = {0, 9218, 19316, 29413, 38631, 49804, 59022, 69658, 79413, 88974, 99609, 108827, 120000};
static const int32_t SCALE_P55[] = {0, 9414, 19609, 29804, 39218, 50196, 59218, 69804, 79609, 89414, 100000, 109022, 120000};
static const int32_t SCALE_P56[] = {0, 9414, 19609, 29804, 39218, 50000, 59218, 69804, 79609, 89414, 100000, 109218, 120000};
static const int32_t SCALE_P57[] = {0, 20391, 35455, 49804, 70196, 90587, 105650, 120000};
static const int32_t SCALE_P58[] = {0, 16500, 31564, 38631, 70196, 81369, 101760, 111120, 120000};
static const int32_t SCALE_P59[] = {0, 9022, 11173, 18240, 20391, 29413, 31564, 38631, 40782, 49804, 51955, 59022, 61173, 70196, 79218, 81369, 88436, 90587, 99609, 101760, 108827, 110978, 120000};
static const int32_t SCALE_P60[] = {0, 23100, 47400, 71700, 95500, 120800};
static const int32_t SCALE_P61[] = {0, 23117, 31564, 47078, 70196, 81369, 96883, 120000};
static const int32_t SCALE_P62[] = {0, 14630, 29261, 43891, 58522, 73152, 87783, 102413, 117043, 131674, 146304, 160935, 175565, 190196};
static const int32_t SCALE_P63[] = {0, 13324, 30185, 43508, 58251, 73693, 88436, 101760, 116502, 131944, 146687, 160011, 176872, 190196};
static const int32_t SCALE_P64[] = {0, 20000, 35000, 50000, 70000, 90000, 105000, 120000};
static const int32_t SCALE_P65[] = {0, 15000, 30000, 50000, 70000, 80000, 100000, 120000};
static const int32_t SCALE_P66[] = {0, 10000, 40000, 50000, 70000, 80000, 110000, 120000};
static const int32_t SCALE_P67[] = {0, 15000, 30000, 40000, 70000, 80000, 100000, 120000};
static const int32_t SCALE_P68[] = {0, 15000, 30000, 50000, 70000, 85000, 100000, 120000};
static const int32_t SCALE_P69[] = {0, 15000, 35000, 55000, 70000, 85000, 105000, 120000};
static const micro_scale_t MICRO_SCALE[] = {
    {5, SCALE_P16}, /* 5EDO */
    {7, SCALE_P17}, /* 7EDO */
    {9, SCALE_P18}, /* 9EDO */
    {10, SCALE_P19}, /* 10EDO */
    {13, SCALE_P20}, /* 13EDO */
    {14, SCALE_P21}, /* 14EDO */
    {15, SCALE_P22}, /* 15EDO */
    {16, SCALE_P23}, /* 16EDO */
    {17, SCALE_P24}, /* 17EDO */
    {18, SCALE_P25}, /* 18EDO */
    {19, SCALE_P26}, /* 19EDO */
    {20, SCALE_P27}, /* 20EDO */
    {21, SCALE_P28}, /* 21EDO */
    {22, SCALE_P29}, /* 22EDO */
    {23, SCALE_P30}, /* 23EDO */
    {24, SCALE_P31}, /* 24EDO */
    {26, SCALE_P32}, /* 26EDO */
    {27, SCALE_P33}, /* 27EDO */
    {29, SCALE_P34}, /* 29EDO */
    {31, SCALE_P35}, /* 31EDO */
    {34, SCALE_P36}, /* 34EDO */
    {36, SCALE_P37}, /* 36EDO */
    {41, SCALE_P38}, /* 41EDO */
    {53, SCALE_P39}, /* 53EDO */
    {7, SCALE_P40}, /* JI-MAJ */
    {7, SCALE_P41}, /* JI-MIN */
    {12, SCALE_P42}, /* JI-12 */
    {12, SCALE_P43}, /* JI-7L */
    {7, SCALE_P44}, /* JI-7 */
    {8, SCALE_P45}, /* HARM8 */
    {16, SCALE_P46}, /* HARM16 */
    {43, SCALE_P47}, /* PARTCH */
    {8, SCALE_P48}, /* HARRIS */
    {12, SCALE_P49}, /* PYTH */
    {12, SCALE_P50}, /* MT-1/4 */
    {12, SCALE_P51}, /* MT-1/3 */
    {12, SCALE_P52}, /* MT-1/6 */
    {12, SCALE_P53}, /* WERCK3 */
    {12, SCALE_P54}, /* KIRN3 */
    {12, SCALE_P55}, /* VALLOT */
    {12, SCALE_P56}, /* YOUNG2 */
    {7, SCALE_P57}, /* RAST-J */
    {8, SCALE_P58}, /* SABA-J */
    {22, SCALE_P59}, /* SHRUTI */
    {5, SCALE_P60}, /* SLENDR */
    {7, SCALE_P61}, /* PELOG */
    {13, SCALE_P62}, /* BP-ET */
    {13, SCALE_P63}, /* BP-JI */
    {7, SCALE_P64}, /* RAST */
    {7, SCALE_P65}, /* BAYATI */
    {7, SCALE_P66}, /* HIJAZ */
    {7, SCALE_P67}, /* SABA */
    {7, SCALE_P68}, /* HUSAYN */
    {7, SCALE_P69}, /* SIKAH */
};
