#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments
"""Generate the USB-only 44.1/48 kHz rational resampler tables (no dependencies).

48-tap Blackman-windowed sinc, 20 kHz cutoff, Q14 with exact unity DC gain.
Each phase is the fraction of an input sample to look back from the latest
sample. The synth's tables and native sample rate are unaffected.
Usage: python3 tools/gen_usb_audio.py > firmware/src/usb_audio_filter.h
"""
import math

TAPS = 48


def generate():
    lines = ["/* Generated by tools/gen_usb_audio.py; do not edit. */",
             "/* SPDX-License-Identifier: GPL-3.0-only */",
             f"#define UA_TAPS {TAPS}u"]
    for name, rate, phases in (("play", 48000, 147), ("cap", 44100, 160)):
        lines.append(f"static const int16_t ua_{name}_filter[{phases}][UA_TAPS] = {{")
        for phase in range(phases):
            delay = (TAPS - 1) / 2 + phase / phases
            coeff = []
            for k in range(TAPS):
                x = 2 * 20000 / rate * (k - delay)
                sinc = math.sin(math.pi * x) / (math.pi * x) if x else 1
                window = (0.42 - 0.5 * math.cos(2 * math.pi * k / (TAPS - 1))
                          + 0.08 * math.cos(4 * math.pi * k / (TAPS - 1)))
                coeff.append(sinc * window)
            scale = 16384 / sum(coeff)
            quantized = [round(c * scale) for c in coeff]
            quantized[round(delay)] += 16384 - sum(quantized)
            # Full-scale PCM16 convolution plus rounding fits signed int32.
            assert sum(abs(c) for c in quantized) < 60000
            lines.append("    {" + ", ".join(map(str, quantized)) + "},")
        lines.append("};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    print(generate(), end="")
