#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Regenerate the CZ envelope fits and 4096-point oscillator table (no runtime float)."""
from pathlib import Path
import math
root = Path(__file__).resolve().parents[1]
text = ['/* SPDX-License-Identifier: GPL-3.0-only */',
        '/* Musical envelope timing fits informed by GPL-3.0 cosmo-pd; see LICENSING.md. */']
tables = [
    ('CZ_PSTEP', [0] + [max(1, round((1 << 24) / (235.64 * math.exp(-13.984 * j / 99) * 44100))) for j in range(1, 100)]),
    ('CZ_STEP', [0] + [max(1, round((1 << 24) / (104.04 * (.004 / 104.04) ** (j / 99) * 44100))) for j in range(1, 100)]),
    ('CZ_PITCH', [round((j / 8 if j <= 64 else 8 + (j - 64) * 2) * 4096) for j in range(100)]),
    ('CZ_GAIN', [round((j / 99) ** 1.5 * 32767) for j in range(100)]),
    ('CZ_DEPTH', [round((j / 99) ** .8 * 65535) for j in range(100)])]
for name, values in tables:
    text.append('static const uint32_t ' + name + '[100] = {\n' + ',\n'.join(','.join(map(str, values[k:k+10])) for k in range(0, 100, 10)) + '\n};')
(root / 'firmware/src/cz1_tables.h').write_text('\n'.join(text) + '\n')
values = [round(math.sin(2 * math.pi * j / 4096) * 32767) for j in range(4096)]
text = '''/* SPDX-License-Identifier: GPL-3.0-only */
/* Generated by tools/gen_cz1_tables.py. Twelve-bit phase lookup in fast RAM. */
#ifdef FM1_IRQ_TARGET
#define CZ_FAST_DATA __attribute__((section(".dsp_data")))
#else
#define CZ_FAST_DATA
#endif
static const int16_t CZ_SINE[4096] CZ_FAST_DATA = {
'''
text += ',\n'.join(','.join(map(str, values[k:k+16])) for k in range(0,4096,16)) + '\n};\n#undef CZ_FAST_DATA\n'
(root / 'firmware/src/cz1_sine.h').write_text(text)
