#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Leo Kuroshita (@kurogedelic), Hügelton Instruments
"""DSP lookup tables for MELODEE (integer controls and native fp32 synths).

FS = 44100 Hz, control rate = every CTL (32) samples. All curves map a
0..127 parameter value to the unit the DSP needs, plus a display table.
"""
import math
import struct
import sys
from pathlib import Path

FS = 44100
CTL = 32


def arr(name, ctype, vals, per=12, ram=False):
    """a table in flash (XIP, through the cache); ram: in RAM (.data), for lookups every sample"""
    out = [f"static {'TABLE_RAM ' if ram else 'const '}{ctype} {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), per):
        out.append("    " + ", ".join(str(v) for v in vals[i:i + per]) + ",")
    out.append("};")
    return out


def f32(x):
    """x rounded to an IEEE single, as C stores a float"""
    return struct.unpack("f", struct.pack("f", x))[0]


def main(path):
    L = ["/* generated by tools/gen_tables.py */", "#pragma once", "#include <stdint.h>",
         f"#define FS {FS}", f"#define CTL {CTL}",
         "#if defined(__APPLE__) || !defined(__clang__) && !defined(__GNUC__)",
         "#define TABLE_RAM                 /* host builds: anywhere */",
         "#else",
         "#define TABLE_RAM __attribute__((section(\".data.tables\")))   /* RAM, not XIP flash: per-sample lookups */",
         "#endif", ""]
    # (1025 points: SINE[i + 1] needs no wrap; the users mask)
    L += arr("SINE", "int16_t", [int(round(32767 * math.sin(2 * math.pi * i / 1024))) for i in range(1025)])
    # phase increment for pitch in 1/16 semitone, MIDI 0..127
    inc = []
    for p in range(128 * 16):
        f = 440.0 * 2 ** ((p / 16 - 69) / 12)
        inc.append(min(int(f / FS * 2 ** 32), 0x7FFFFFFF))
    # stored as its top octave (1856..2047) shifted down: floor(floor(x) / 2^k) = floor(x / 2^k), so
    # pitch_inc(p) equals the 2048-entry table bit for bit (checked here); 7.4 KB less flash
    oct_ = inc[1856:2048]
    assert all(inc[q] == oct_[(q + 64) % 192] >> (10 - (q + 64) // 192) for q in range(2048))
    assert all((q + 64) * 21846 >> 22 == (q + 64) // 192 for q in range(2048))
    L += arr("PITCH_OCT", "uint32_t", oct_, 8)
    # Device concert pitch: exact frequency ratios and FM6's Q24 octave offsets.
    L += arr("A4_RATIO", "uint32_t", [round((1 << 24) * hz / 440) for hz in range(400, 481)], 8)
    L += arr("A4_LOG", "int32_t", [round((1 << 24) * math.log2(hz / 440)) for hz in range(400, 481)], 8)
    L += ["/* phase increment of pitch p in 1/16 semitone, 0..2047 (MIDI 0..127): 440 Hz * 2^((p / 16 - 69) / 12) */",
          "static inline uint32_t pitch_inc(uint32_t p)",
          "{",
          "    uint32_t i = p + 64u, o = (i * 21846u) >> 22;     /* i / 192: the octave above PITCH_OCT's - 10 */",
          "    return PITCH_OCT[i - o * 192u] >> (10u - o);",
          "}"]
    # times 1 ms .. 10 s (exponential), env in Q24 (1.0 = 1<<24)
    ms = [1.0 * (10000 ** (v / 127)) for v in range(128)]
    L += arr("TIME_MS_X10", "uint32_t", [int(round(m * 10)) for m in ms], 10)
    L += arr("ENV_LIN", "uint32_t", [max(1, int((1 << 24) * CTL / (m * FS / 1000))) for m in ms], 8)
    exp_k = []
    for m in ms:
        tau = m / 1000 / 4.6                       # ~99 % of the way after "m" ms
        exp_k.append(max(1, min(65535, int(65536 * (1 - math.exp(-CTL / (tau * FS)))))))
    L += arr("ENV_EXP", "uint16_t", exp_k)
    # LFO 0.05 .. 40 Hz, phase increment per control tick
    hz = [0.05 * (800 ** (v / 127)) for v in range(128)]
    L += arr("LFO_HZ_X100", "uint32_t", [int(round(h * 100)) for h in hz], 10)
    L += arr("LFO_INC", "uint32_t", [int(h * CTL / FS * 2 ** 32) for h in hz], 8)
    # filter cutoff 30 Hz .. 16 kHz
    fc = [30.0 * ((16000 / 30) ** (v / 127)) for v in range(128)]
    L += arr("CUTOFF_HZ", "uint16_t", [int(round(f)) for f in fc])
    # trapezoidal (Simper) SVF: g = tan(pi fc / FS), Q12; stable at any cutoff/resonance
    L += arr("SVF_G", "uint16_t", [int(4096 * math.tan(math.pi * min(f, 0.45 * FS) / FS)) for f in fc])
    L += ["#if !defined(MELODEE_PROPHET) || MELODEE_PROPHET"]
    L += [f"#define P5_KEYTRACK_HALF_Q7 {round(128 * 256 * 127 * math.log(2) / (2 * 192 * math.log(fc[-1] / fc[0])))}"]
    # LFO rate, raw 0..127. Measured on a Rev-4 factory demo (rates 74..97 -> 2.4..8.4 Hz,
    # within 2 %): ln Hz = -3.1005 + 0.05387 raw, bent at the ends to the documented .022 / 500 Hz.
    def p5_lfo_hz(v):
        x = -3.1005 + 0.05387 * v
        if v > 100:
            x += (math.log(500) - (-3.1005 + 0.05387 * 127)) * ((v - 100) / 27) ** 2
        if v < 20:
            x -= (-3.1005 - math.log(.022)) * ((20 - v) / 20) ** 2
        return math.exp(x)
    L += arr("P5_LFO_INC", "uint32_t", [int(p5_lfo_hz(v) / FS * 2**32) for v in range(128)], 8)
    # LFO amount response (initial + wheel + pressure), normalized. Rev-4 vibrato depth measured at
    # 18..55 fits 0.0519 * raw^1.737 cents; the full scale (235 cents) lives in the engine.
    L += arr("P5_AMOUNT", "float", [f"{(v / 127) ** 1.737:.9e}f" for v in range(128)])
    # Keep the calibrated times, without quantizing rates to Q24/Q16.
    p5ms = [10000 ** (v / 127) for v in range(128)]
    L += arr("P5_ENV_ATK", "float", [f"{CTL / (m * FS / 1000):.9e}f" for m in p5ms])
    L += arr("P5_ENV_EXP", "float", [f"{1 - math.exp(-CTL / (m / 1000 * FS)):.9e}f" for m in p5ms])
    L += arr("P5_ENV_SSM", "float", [f"{CTL / (3.6 * m * FS / 1000):.9e}f" for m in p5ms])
    # TPT coefficients at the selected oversampling rate. Keep this small
    # RAM table for audio-rate Poly-Mod; feedback division and tanh use fp32.
    for os in (2, 1):
        L += ["#if P5_OVERSAMPLE == 2" if os == 2 else "#else"]
        vals = [math.tan(math.pi * f / (os * FS)) / (1 + math.tan(math.pi * f / (os * FS))) for f in fc]
        g = arr("P5_TPT_G", "float", [f"{v:.9e}f" for v in vals])
        g[0] = g[0].replace(" =", ' __attribute__((section(".dsp_tables"))) =')
        L += g
    L += ["#endif"]  # oversampling
    tanh = arr("P5_TANH", "float", [f"{math.tanh(i / 128):.9e}f" for i in range(1025)])
    tanh[0] = tanh[0].replace(" =", ' __attribute__((section(".dsp_tables"))) =')
    L += tanh
    exp2 = arr("P5_EXP2", "float", [f"{2 ** (i / 512):.9e}f" for i in range(514)])
    exp2[0] = exp2[0].replace(" =", ' __attribute__((section(".dsp_tables"))) =')
    L += exp2
    L += ["#endif"]
    # level: 0 = off, else dB = (v - 112) / 2  (112 = 0 dB, 127 = +7.5 dB)
    db = [None] + [(v - 112) / 2 for v in range(1, 128)]
    L += arr("LEVEL_Q12", "uint16_t", [0] + [int(round(4096 * 10 ** (d / 20))) for d in db[1:]])
    L += arr("LEVEL_DB_X10", "int16_t", [-999] + [int(round(d * 10)) for d in db[1:]])
    # per-sample exponential decay for drum voices: 5 ms .. 4 s to -60 dB, Q16
    dms = [5.0 * (800 ** (v / 127)) for v in range(128)]
    L += arr("DECAY_K", "uint16_t", [min(65535, int(65536 * math.exp(-6.9 / (m / 1000 * FS)))) for m in dms])
    # soft clip curve for |x| in 0..2 (Q12 in, Q15 out): tanh
    L += arr("TANH_Q15", "int16_t", [int(32767 * math.tanh(i / 256 * 2)) for i in range(257)])
    L += fm6_tables()
    L += sid_tables()
    Path(path).write_text("\n".join(L) + "\n")
    print(f"tables: {path}")


SID_CLOCK = 985248                                  # PAL C64: 17.734475 MHz / 18
SID_WAVES = Path(__file__).resolve().parent.parent / "assets/resid"   # reSID's combined waveforms (its README)
SID_RATE = [9, 32, 63, 95, 149, 220, 267, 313, 392, 977, 1954, 3126, 3907, 11720, 19532, 31251]


def sid_dac_bits(bits, r2r, term):
    """reSID 1.0 dac.cc build_dac_table: the voltage each bit of an R-2R ladder gives on its own, 2R / R = r2r,
    term: terminated (8580) or not (6581); any code is the sum of its bits (superposition)"""
    vbit = []
    for set_bit in range(bits):
        vn, r, r2 = 1.0, 1.0, r2r
        rn = r2 if term else math.inf
        for _ in range(set_bit):                    # the "tail" below the bit, by parallel substitution
            rn = r + r2 if rn == math.inf else r + r2 * rn / (r2 + rn)
        if rn == math.inf:                          # source transformation for the bit's voltage
            rn = r2
        else:
            rn = r2 * rn / (r2 + rn)
            vn = vn * rn / r2
        for _ in range(set_bit + 1, bits):          # up to the output, by repeated source transformation
            rn += r
            i = vn / rn
            rn = r2 * rn / (r2 + rn)
            vn = rn * i
        vbit.append(vn * ((1 << bits) - 1))
    return vbit


def sid_spline(points):
    """reSID 0.16 spline.h interpolate(): piecewise cubic through (x, y), repeated end points; y at x = 0..2047"""
    y = [0.0] * 2048
    for j in range(len(points) - 3):
        (x0, y0), (x1, y1), (x2, y2), (x3, y3) = points[j:j + 4]
        if x1 == x2:
            continue
        if x0 == x1 and x2 == x3:
            k1 = k2 = (y2 - y1) / (x2 - x1)
        elif x0 == x1:
            k2 = (y3 - y1) / (x3 - x1)
            k1 = (3 * (y2 - y1) / (x2 - x1) - k2) / 2
        elif x2 == x3:
            k1 = (y2 - y0) / (x2 - x0)
            k2 = (3 * (y2 - y1) / (x2 - x1) - k1) / 2
        else:
            k1 = (y2 - y0) / (x2 - x0)
            k2 = (y3 - y1) / (x3 - x1)
        dx, dy = x2 - x1, y2 - y1                   # cubic with f(x1) = y1, f(x2) = y2, f'(x1) = k1, f'(x2) = k2
        a = ((k1 + k2) - 2 * dy / dx) / dx ** 2
        b = ((k2 - k1) / dx - 3 * (x1 + x2) * a) / 2
        c = k1 - (3 * x1 * a + 2 * b) * x1
        d = y1 - ((x1 * a + b) * x1 + c) * x1
        for x in range(x1, x2 + 1):
            y[x] = ((a * x + b) * x + c) * x + d
    return y


def sid_lz(t):
    """eng_sid.c sid_unpack's format: c < 0x80: c + 1 bytes follow; c >= 0x80: (c & 0x7f) + 3 bytes copied from
    d + 1 back, d in the next two bytes (little endian). Greedy longest match within the table"""
    out, lit, i = bytearray(), bytearray(), 0

    def flush():
        while lit:
            k = min(len(lit), 128)
            out.append(k - 1)
            out.extend(lit[:k])
            del lit[:k]
    while i < len(t):
        best, dist = 0, 0
        for d in range(1, min(i, 4096) + 1):
            n = 0
            while n < 130 and i + n < len(t) and t[i + n] == t[i + n - d]:
                n += 1
            if n > best:
                best, dist = n, d
                if n == 130:
                    break
        if best >= 3:
            flush()
            out += bytes([0x80 | (best - 3), (dist - 1) & 0xff, (dist - 1) >> 8])
            i += best
        else:
            lit.append(t[i])
            i += 1
    flush()
    return bytes(out)


def sid_unlz(b, n):
    o, i = bytearray(), 0
    while len(o) < n:
        c = b[i]
        if c < 0x80:
            o += b[i + 1:i + c + 2]
            i += c + 2
        else:
            d = b[i + 1] + (b[i + 2] << 8) + 1
            for _ in range((c & 0x7f) + 3):
                o.append(o[-d])
            i += 3
    return bytes(o)


def sid_tables():
    """SID (eng_sid.c): the MOS 6581 / 8580 as reSID models them (Dag Lem, reSID 0.16 and 1.0, GPL-2.0-or-later)"""
    L = []
    # waveform DAC (12 bits) and envelope DAC (8 bits): the 6581's ladders are 2R / R = 2.20 without termination
    # (bit 0 weighs 2.07, bit 11 1983 of 4095: uneven steps, 0x7FF above 0x800), the 8580's exact. Waveform: code ->
    # DAC x 4 (0..16380) as LO[code & 63] + HI[code >> 6]; envelope: Q15 (full = 32767) as LO[e & 15] + HI[e >> 4]
    for name, bits, half, scale in (("SID_WDAC", 12, 6, 4.0), ("SID_EDAC", 8, 4, None)):
        rows = []
        for r2r, term in ((2.20, False), (2.00, True)):
            vb = sid_dac_bits(bits, r2r, term)
            s = scale if scale else 32767 / sum(vb)
            for part in (vb[:half], vb[half:]):
                rows.append([int(round(s * sum(w for j, w in enumerate(part) if code >> j & 1)))
                             for code in range(1 << half)])
        L += [f"static const int16_t {name}[2][2][{1 << half}] = {{   /* [6581, 8580][low, high bits] */"]
        for m in range(2):
            L += ["    {" + ", ".join("{" + ", ".join(str(v) for v in rows[2 * m + h]) + "}" for h in range(2)) + "},"]
        L += ["};"]
    # filter cutoff: reSID 0.16's measured curves, FC (11 bits) -> Hz, spline-interpolated; the 6581's has its jump
    # at FC 0x400. As g = tan(pi f / FS) (Q12) at FC = 16 i (i = 128: FC 2047), linear between
    f6581 = [(0, 220), (0, 220), (128, 230), (256, 250), (384, 300), (512, 420), (640, 780), (768, 1600), (832, 2300),
             (896, 3200), (960, 4300), (992, 5000), (1008, 5400), (1016, 5700), (1023, 6000), (1023, 6000),
             (1024, 4600), (1024, 4600), (1032, 4800), (1056, 5300), (1088, 6000), (1120, 6600), (1152, 7200),
             (1280, 9500), (1408, 12000), (1536, 14500), (1664, 16000), (1792, 17100), (1920, 17700), (2047, 18000),
             (2047, 18000)]
    f8580 = [(0, 0), (0, 0), (128, 800), (256, 1600), (384, 2500), (512, 3300), (640, 4100), (768, 4800), (896, 5600),
             (1024, 6500), (1152, 7500), (1280, 8400), (1408, 9200), (1536, 9800), (1664, 10500), (1792, 11000),
             (1920, 11700), (2047, 12500), (2047, 12500)]
    L += ["static const uint16_t SID_FC_G[2][129] = {   /* [6581, 8580] */"]
    for pts in (f6581, f8580):
        hz = sid_spline(pts)
        g = [int(round(4096 * math.tan(math.pi * min(max(hz[min(16 * i, 2047)], 0.0), 0.45 * FS) / FS)))
             for i in range(129)]
        L += ["    {" + ", ".join(str(v) for v in g) + "},"]
    L += ["};"]
    # resonance (4 bits) -> SVF damping 1/Q, Q12. 6581 (reSID 1.0 filter.h): its ladder gives 1/Q = ~res / 8 (Q 0.53
    # .. 8, unbounded at 15), which its low-gain op-amps never reach: a loss of 1/4 keeps Q <= 4. 8580: 1/Q =
    # 2^((4 - res) / 8): Q 0.71 .. 2.6
    k6581 = [int(round(4096 * ((15 - r) / 8 + 0.25))) for r in range(16)]
    k8580 = [int(round(4096 * 2 ** ((4 - r) / 8))) for r in range(16)]
    L += ["static const uint16_t SID_RES_K[2][16] = {{" + ", ".join(map(str, k6581)) + "}, {" +
          ", ".join(map(str, k8580)) + "}};"]
    # the track's ADSR (0..127: 1 ms .. 10 s) -> the nearest of SID's 16 rates (log time): attack 255 steps,
    # decay / release 756 rate periods (the exponential counter's 1 2 4 8 16 30). Low nibble attack, high decay
    def exp_period(c):
        return 1 if c > 0x5d else 2 if c > 0x36 else 4 if c > 0x1a else 8 if c > 0x0e else 16 if c > 0x06 else 30
    steps_dr = sum(exp_period(c) for c in range(255, 0, -1))
    att = [math.log(r * 255 / SID_CLOCK) for r in SID_RATE]
    dr = [math.log(r * steps_dr / SID_CLOCK) for r in SID_RATE]
    near = lambda tab, x: min(range(16), key=lambda r: abs(tab[r] - x))
    L += arr("SID_ADSR_RATE", "uint8_t",
             [near(att, math.log(10 ** (4 * v / 127) / 1000)) | near(dr, math.log(10 ** (4 * v / 127) / 1000)) << 4
              for v in range(128)], 16)
    # combined waveforms: reSID's samples of a real 6581 and 8580 (assets/resid/README.md), the top 8 of 12 output
    # bits by accumulator >> 12 for TRI+SAW, TRI+PULSE, SAW+PULSE, all three; packed (sid_lz, checked here)
    packed, at = bytearray(), []
    for m in ("6581", "8580"):
        for w in ("_ST", "P_T", "PS_", "PST"):
            t = (SID_WAVES / f"wave{m}_{w}.dat").read_bytes()
            e = sid_lz(t)
            assert len(t) == 4096 and sid_unlz(e, 4096) == t
            at.append(len(packed))
            packed += e
    L += arr("SID_WAVE_LZ", "uint8_t", list(packed), 24)
    L += ["static const uint16_t SID_WAVE_AT[2][4] = {{" + ", ".join(map(str, at[:4])) + "}, {" +
          ", ".join(map(str, at[4:])) + "}};   /* [6581, 8580][TRI+SAW, TRI+PULSE, SAW+PULSE, all] */"]
    # clocks: SID cycles per control tick (Q16), 32-bit phase step per frequency register unit (Q16), its inverse
    # (Q32); the C64's output stage: 16 kHz RC low pass (Q15), 16 Hz coupling capacitor (Q16) (reSID extfilt)
    L += [f"#define SID_CYC_Q16 {round(SID_CLOCK * CTL * 65536 / FS)}u",
          f"#define SID_FREQ_K16 {round(SID_CLOCK * 256 * 65536 / FS)}u",
          f"#define SID_FREQ_R32 {round(2 ** 32 * FS / (SID_CLOCK * 256))}u",
          f"#define SID_XLP_A {round(32768 * (1 - math.exp(-100000 / FS)))}",
          f"#define SID_XHP_A {round(65536 * (1 - math.exp(-100 / FS)))}"]
    return L


def fm6_tables():
    """FM6 (eng_fm6.c): Dexed's lookup tables, computed as Dexed computes them at 44.1 kHz with its
    64-sample blocks (MSFA sin.cc, exp2.cc, freqlut.cc, lfo.cc, pitchenv.cc, porta.cpp, dx7note.cc,
    EngineMkI.cpp; Apache License 2.0 / GPL-3.0-or-later, see LICENSING.md), so FM6 renders the same
    samples. Logs in Q24 (1 << 24 = one octave)."""
    N = 64
    L = [f"#define FM6_N {N}", "#define FM6_LG_N 6"]
    # sine, Q24 out of a Q24 phase: 1024 points by rotation (sin.cc), the next point for interpolation
    c = math.floor(math.cos(2 * math.pi / 1024) * (1 << 30) + 0.5)
    s = math.floor(math.sin(2 * math.pi / 1024) * (1 << 30) + 0.5)
    u, v, sin_t = 1 << 30, 0, [0] * 1025
    for i in range(512):
        sin_t[i] = (v + 32) >> 6
        sin_t[i + 512] = -((v + 32) >> 6)
        u, v = (u * c - v * s + (1 << 29)) >> 30, (u * s + v * c + (1 << 29)) >> 30
    L += arr("FM6_SIN", "float", [f"{v / 2**24:.9e}f" for v in sin_t], 8, ram=True)
    # Exact integer phase steps for Q24 log pitches (Freqlut). The continuous
    # signal path is float, but float cannot carry every bit of this pitch.
    y, inc, fl = float(1 << 44) / FS, math.pow(2, 1.0 / 1024), []
    for i in range(1025):
        fl.append(math.floor(y + 0.5))
        y *= inc
    L += arr("FM6_FREQ", "int32_t", fl, 8)
    # MARK I (EngineMkI.cpp): log sine (1/1024 octave) and exponent tables, made in float
    lg = [int(round(f32(-1024 * f32(math.log2(f32(math.sin(((0.5 + i) / 1024.0) * math.pi / 2.0)))))))
          for i in range(1024)]
    ex = [int(round(f32((math.pow(2, f32(i / 1024.0)) - 1) * 4096))) for i in range(1024)]
    L += arr("FM6_MKI_LOG", "uint16_t", lg + lg[::-1], 16, ram=True)    # half a cycle (the sign: the phase)
    L += arr("FM6_MKI_EXP", "uint16_t", [4096 + ex[i ^ 1023] for i in range(1024)], 16, ram=True)   # 4096 + exp, reversed
    # OPL (EngineOpl.cpp): the OPL's quarter-wave log sine and exponent ROMs
    opl_log = [
        2137, 1731, 1543, 1419, 1326, 1252, 1190, 1137, 1091, 1050, 1013, 979, 949, 920, 894, 869,
        846, 825, 804, 785, 767, 749, 732, 717, 701, 687, 672, 659, 646, 633, 621, 609,
        598, 587, 576, 566, 556, 546, 536, 527, 518, 509, 501, 492, 484, 476, 468, 461,
        453, 446, 439, 432, 425, 418, 411, 405, 399, 392, 386, 380, 375, 369, 363, 358,
        352, 347, 341, 336, 331, 326, 321, 316, 311, 307, 302, 297, 293, 289, 284, 280,
        276, 271, 267, 263, 259, 255, 251, 248, 244, 240, 236, 233, 229, 226, 222, 219,
        215, 212, 209, 205, 202, 199, 196, 193, 190, 187, 184, 181, 178, 175, 172, 169,
        167, 164, 161, 159, 156, 153, 151, 148, 146, 143, 141, 138, 136, 134, 131, 129,
        127, 125, 122, 120, 118, 116, 114, 112, 110, 108, 106, 104, 102, 100, 98, 96,
        94, 92, 91, 89, 87, 85, 83, 82, 80, 78, 77, 75, 74, 72, 70, 69,
        67, 66, 64, 63, 62, 60, 59, 57, 56, 55, 53, 52, 51, 49, 48, 47,
        46, 45, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30,
        29, 28, 27, 26, 25, 24, 23, 23, 22, 21, 20, 20, 19, 18, 17, 17,
        16, 15, 15, 14, 13, 13, 12, 12, 11, 10, 10, 9, 9, 8, 8, 7,
        7, 7, 6, 6, 5, 5, 5, 4, 4, 4, 3, 3, 3, 2, 2, 2,
        2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    L += arr("FM6_OPL_LOG", "uint16_t", opl_log + opl_log[::-1], 16, ram=True)  # half a cycle
    opl_exp = [
        0, 3, 6, 8, 11, 14, 17, 20, 22, 25, 28, 31, 34, 37, 40, 42,
        45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90,
        93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 130, 133, 136, 139,
        142, 145, 148, 152, 155, 158, 161, 164, 168, 171, 174, 177, 181, 184, 187, 190,
        194, 197, 200, 204, 207, 210, 214, 217, 220, 224, 227, 231, 234, 237, 241, 244,
        248, 251, 255, 258, 262, 265, 268, 272, 276, 279, 283, 286, 290, 293, 297, 300,
        304, 308, 311, 315, 318, 322, 326, 329, 333, 337, 340, 344, 348, 352, 355, 359,
        363, 367, 370, 374, 378, 382, 385, 389, 393, 397, 401, 405, 409, 412, 416, 420,
        424, 428, 432, 436, 440, 444, 448, 452, 456, 460, 464, 468, 472, 476, 480, 484,
        488, 492, 496, 501, 505, 509, 513, 517, 521, 526, 530, 534, 538, 542, 547, 551,
        555, 560, 564, 568, 572, 577, 581, 585, 590, 594, 599, 603, 607, 612, 616, 621,
        625, 630, 634, 639, 643, 648, 652, 657, 661, 666, 670, 675, 680, 684, 689, 693,
        698, 703, 708, 712, 717, 722, 726, 731, 736, 741, 745, 750, 755, 760, 765, 770,
        774, 779, 784, 789, 794, 799, 804, 809, 814, 819, 824, 829, 834, 839, 844, 849,
        854, 859, 864, 869, 874, 880, 885, 890, 895, 900, 906, 911, 916, 921, 927, 932,
        937, 942, 948, 953, 959, 964, 969, 975, 980, 986, 991, 996, 1002, 1007, 1013, 1018]
    L += arr("FM6_OPL_EXP", "uint16_t", [(0x400 + opl_exp[i ^ 0xFF]) << 1 for i in range(256)], 16, ram=True)
    # frequency: coarse ratios, fine (dx7note.cc osc_freq), detune per note x (DET - 7) in Q24 fractions
    L += arr("FM6_COARSE", "int32_t", [-(1 << 24)] + [int(round((1 << 24) * math.log2(k))) for k in range(1, 32)], 8)
    L += arr("FM6_FINE", "int32_t", [math.floor(24204406.323123 * math.log(1 + 0.01 * f) + 0.5) for f in range(128)], 8)
    det = []
    for n in range(128):
        lf = 50857777 + ((1 << 24) // 12) * n                       # Dexed's standard tuning
        r = 0.0209 * math.exp(-0.396 * (f32(float(lf)) / (1 << 24))) / 7
        det.append(round(r * lf * (1 << 24)))
        for d in range(16):                                          # the table gives Dexed's result
            want = int(lf + r * lf * (d - 7)) - lf
            assert lf + ((det[-1] * (d - 7)) >> 24) - lf == want, (n, d)
    L += arr("FM6_DETUNE", "int64_t", det, 6)
    # LFO speeds (lfo.cc): Hz measured on a DX7 (MSFA, Copyright 2012 Google Inc.), as Dexed's phase
    # increments per 64-sample block
    hz = [0.062541, 0.125031, 0.312393, 0.437120, 0.624610, 0.750694, 0.936330, 1.125302, 1.249609, 1.436782,
          1.560915, 1.752081, 1.875117, 2.062494, 2.247191, 2.374451, 2.560492, 2.686728, 2.873976, 2.998950,
          3.188013, 3.369840, 3.500175, 3.682224, 3.812065, 4.000800, 4.186202, 4.310716, 4.501260, 4.623209,
          4.814636, 4.930480, 5.121901, 5.315191, 5.434783, 5.617346, 5.750431, 5.946717, 6.062811, 6.248438,
          6.431695, 6.564264, 6.749460, 6.868132, 7.052186, 7.250580, 7.375719, 7.556294, 7.687577, 7.877738,
          7.993605, 8.181967, 8.372405, 8.504848, 8.685079, 8.810573, 8.986341, 9.122423, 9.300595, 9.500285,
          9.607994, 9.798158, 9.950249, 10.117361, 11.251125, 11.384335, 12.562814, 13.676149, 13.904338,
          15.092062, 16.366612, 16.638935, 17.869907, 19.193858, 19.425019, 20.833333, 21.034918, 22.502250,
          24.003841, 24.260068, 25.746653, 27.173913, 27.578599, 29.052876, 30.693677, 31.191516, 32.658393,
          34.317090, 34.674064, 36.416606, 38.197097, 38.550501, 40.387722, 40.749796, 42.625746, 44.326241,
          44.883303, 46.772685, 48.590865, 49.261084]
    assert len(hz) == 100
    ratio = int(4437500000.0 * N / FS)
    L += arr("FM6_LFO_INC", "uint32_t", [int(h * ratio) for h in hz], 8)
    L += [f"#define FM6_LFO_UNIT {int(N * 25190424 / FS + 0.5)}",
          f"#define FM6_PEG_UNIT {int(N * (1 << 24) / (21.3 * FS) + 0.5)}"]
    # portamento (porta.cpp): pitch steps per block, plain and glissando, for CC 5 = 0..127
    def porta(sps):
        return [int(0.5 + ((1 << 24) // 12) * (sps * math.pow(2.0, -0.062 * i) / FS * N)) for i in range(128)]
    L += arr("FM6_PORTA", "int32_t", porta(2100.0), 8)
    L += arr("FM6_GLISS", "int32_t", porta(1300.0), 8)
    return L


if __name__ == "__main__":
    main(sys.argv[1])
