#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""CZ-1's factory tones: assets/cz1-factory/cz1-factory.syx (64 native CZ-1 tones, Casio's preset tones
A-1 .. H-8; tools/make_cz1_factory.py) -> a header for eng_cz.c:

  CZ_FACTORY[64][144]   the native tones (128 synthesis bytes + the 16-character LCD name)
  CZ_FACTORY_PRESETS(X) X(name, bank, ptch, pattern) for each: the PRESETS list (12-character names),
                        BANK A..D, PTCH 1..16 (cz_bank.c holds them as the default BANK A..D)

  tools/gen_cz1_factory.py OUT.h
"""
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "assets/cz1-factory/cz1-factory.syx"
SHORT = {"FUNKY CLAVI.1": "FUNKY CLAV 1", "FUNKY CLAVI.2": "FUNKY CLAV 2", "AFRO-PERCUSSION": "AFRO PERC",
         "METALLIC SOUND": "METALLIC", "SYNTH.STRINGS": "SYN STRINGS", "SWEEP SOUND 1": "SWEEP 1",
         "SWEEP SOUND 2": "SWEEP 2", "SYNTH.DRUMS 1": "SYN DRUMS 1", "SYNTH.DRUMS 2": "SYN DRUMS 2",
         "TYPHOON SOUND": "TYPHOON"}
# suggested pattern (seq.c PATTERNS: 2 OFFBEAT 3 MELODY 4 LEAD 5 PAD 6 KEYS 7 BELL), per CZ-1 preset group
PAT = [4, 4, 4, 5, 5, 5, 5, 5, 3, 3, 3, 2, 2, 2, 2, 3,
       4, 4, 3, 3, 4, 4, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 5, 5, 6, 5, 5, 5, 7, 7, 7, 7, 7, 3, 7, 7,
       5, 5, 3, 4, 4, 4, 4, 5, 3, 3, 3, 7, 5, 5, 5, 5]


def valid(b):
    """cz_patch.h cz_patch_valid"""
    if (b[0] & 0xF0) or (b[0] >> 2) > 2 or b[1] > 1 or (b[2] & 3) or b[3] > 47:
        return False
    for off in (0, 57):
        if (b[16 + off] & 15) > 9 or (b[16 + off] >> 4) > 14 or b[18 + off] > 9:
            return False
    return not any(b[e] & 8 for e in (54, 37, 20, 111, 94, 77))


def tones():
    raw = SRC.read_bytes()
    if len(raw) != 64 * 296:
        raise SystemExit(f"{SRC}: {len(raw)} B, want 64 CZ-1 tone dumps of 296 B")
    out = []
    for k in range(64):
        m = raw[k * 296:(k + 1) * 296]
        if m[:6] != bytes([0xF0, 0x44, 0, 0, 0x70, 0x21]) or m[-1] != 0xF7 or any(x > 15 for x in m[7:-1]):
            raise SystemExit(f"{SRC}: tone {k + 1} is not a CZ-1 tone dump")
        t = bytes(m[7 + 2 * i] | m[8 + 2 * i] << 4 for i in range(144))
        if not valid(t) or not all(32 <= c <= 126 for c in t[128:]):
            raise SystemExit(f"{SRC}: tone {k + 1} is not a valid native tone")
        out.append(t)
    return out


def main(path):
    ts = tones()
    L = ["/* generated by tools/gen_cz1_factory.py from assets/cz1-factory/cz1-factory.syx:",
         " * Casio's 64 CZ-1 preset tones (A-1 .. H-8), native 144-byte tones */",
         f"#define CZ_FACTORY_N {len(ts)}u",
         f"static const uint8_t CZ_FACTORY[{len(ts)}][144] = {{"]
    for t in ts:
        L.append("    {" + ",".join(str(x) for x in t) + "},")
    L += ["};", "#define CZ_FACTORY_PRESETS(X) \\"]
    for k, t in enumerate(ts):
        name = t[128:].decode("ascii").strip()
        short = SHORT.get(name, name)
        if len(short) > 12:
            raise SystemExit(f"{name}: preset name over 12 characters")
        L.append(f'    X("{short}", {k // 16}, {k % 16 + 1}, {PAT[k]}) \\')
    L.append("")
    Path(path).write_text("\n".join(L) + "\n")
    print(f"cz1 factory: {len(ts)} tones -> {path}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
