#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate the append-only SCL catalogue, offline. --check verifies checked-in outputs."""
import argparse
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "assets/scales"


def scala(path):
    lines = [s.strip() for s in path.read_text().splitlines() if not s.lstrip().startswith("!")]
    count = int(lines[1])
    pitches = []
    for line in lines[2:]:
        if not line:
            continue
        token = line.split()[0]
        if "." in token:
            cents = float(token)
        else:
            numerator, _, denominator = token.partition("/")
            cents = 1200 * math.log2(int(numerator) / int(denominator or 1))
        pitches.append(cents)
        if len(pitches) == count:
            break
    if len(pitches) != count:
        raise ValueError(f"Incomplete scale: {path}")
    return pitches


def catalogue():
    rows = json.loads((DATA / "catalog.json").read_text())
    for i, row in enumerate(rows):
        assert len(row["name"]) <= 7 and row["name"].isascii()
        if "notes" in row:
            assert i < 16
            values = [100 * n for n in row["notes"]][1:] + [1200]
        elif "edo" in row:
            values = [1200 * n / row["edo"] for n in range(1, row["edo"] + 1)]
        elif "file" in row:
            values = scala(DATA / row["file"])
        else:
            values = row["cents"]
        row["pitch"] = [0] + [round(v * 100) for v in values]
        assert 1 <= len(values) <= 53 and all(a < b for a, b in zip(row["pitch"], row["pitch"][1:]))
    assert len(rows) <= 96 and len({r["name"] for r in rows}) == len(rows)
    return rows


def main():
    check = argparse.ArgumentParser()
    check.add_argument("--check", action="store_true")
    args = check.parse_args()
    rows = catalogue()
    groups = list(dict.fromkeys(r['group'] for r in rows))
    short = ['WEST', 'EDO', 'JUST', 'HARM', 'HIST', 'WORLD', 'BP', 'MAQAM']
    assert len(groups) == len(short)
    info = [dict(name=r['name'], title=r['title'], family='Western' if r['group'] == 'Original' else r['group'], count=len(r['pitch']) - 1) for r in rows]
    names = json.dumps([r["name"] for r in rows])
    output = ["/* SPDX-License-Identifier: GPL-3.0-only */", "/* Generated by tools/gen_scales.py; edit assets/scales/catalog.json. */",
              "#pragma once", "#define SCALE_LEGACY 16u", f"#define SCALE_TOTAL {len(rows)}u",
              "static const char *const N_SCALE[] = {" + names[1:-1] + "};",
              "static const char *const SCALE_TITLE[] = {" + json.dumps([r['title'] for r in rows])[1:-1] + "};",
              "static const uint8_t SCALE_DEGREES[] = {" + ', '.join(str(r['count']) for r in info) + "};",
              "static const uint8_t SCALE_FAMILY[] = {" + ', '.join(str(groups.index(r['group'])) for r in rows) + "};",
              f"#define SCALE_FAMILIES {len(groups)}u",
              "static const char *const SCALE_FAMILY_SHORT[] = {\"ALL\", " + json.dumps(short)[1:-1] + ", \"FAV\"};",
              "static const char *const SCALE_FAMILY_TITLE[] = {" + json.dumps(['All scales'] + ['Western' if g == 'Original' else g for g in groups] + ['Favorites'])[1:-1] + "};",
              "typedef struct { uint8_t count; const int32_t *pitch; } micro_scale_t;"]
    output += ["static const uint16_t SCALE_MASK[] = {" + ", ".join(hex(sum(1 << n for n in r["notes"])) for r in rows[:16]) + "};"]
    for i, row in enumerate(rows[16:], 16):
        output.append(f"static const int32_t SCALE_P{i}[] = {{" + ", ".join(map(str, row["pitch"])) + "};")
    output += ["static const micro_scale_t MICRO_SCALE[] = {"]
    output += [f"    {{{len(row['pitch']) - 1}, SCALE_P{i}}}, /* {row['name']} */" for i, row in enumerate(rows[16:], 16)]
    output += ["};", ""]
    header = ROOT / "firmware/src/scales.h"
    web = ROOT / "web/editor.html"
    html = web.read_text()
    html = re.sub(r'const SCALE_INFO = .*?; /\* generated scale metadata \*/', 'const SCALE_INFO = ' + json.dumps(info) + '; /* generated scale metadata */', html)
    html = re.sub(r'E\("SCL", \[[^\]]*\], 0\)', f'E("SCL", {names}, 0)', html)
    html = re.sub(r"const SCALE_DEGREES = \[[^\]]*\]; /\* generated scale degree counts \*/",
                  "const SCALE_DEGREES = " + json.dumps([len(r["pitch"]) - 1 for r in rows]) + "; /* generated scale degree counts */", html)
    for path, content in [(header, "\n".join(output)), (web, html)]:
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale scale catalogue: {path}")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
