#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Exact Sequential v1.03 programs -> factory presets and mock data."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/prophet5-factory/prophet5-v1.03.syx"
SHA256 = "1d6e9dec2753a08ac6d07b98f0f4e755e33b41de11dc3bed46fa23217619d232"
BEGIN = "/*P5-FACTORY-BEGIN*/"
END = "/*P5-FACTORY-END*/"


def records():
    data = SOURCE.read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA256 or len(data) != 200 * 159:
        raise ValueError("Sequential v1.03 source checksum or bank length changed")
    result = []
    for k in range(200):
        frame = data[k * 159:(k + 1) * 159]
        if frame[:4] != bytes([240, 1, 50, 2]) or frame[-1] != 247 or any(x > 127 for x in frame[1:-1]):
            raise ValueError(f"Invalid native frame {k + 1}")
        if frame[4] != k // 40 or frame[5] != k % 40:
            raise ValueError(f"Unexpected native address {k + 1}")
        packed = frame[6:-1]
        raw = bytes(packed[i + j + 1] | ((packed[i] >> j & 1) << 7)
                    for i in range(0, 152, 8) for j in range(7))
        result.append(raw + bytes([133, 50, 2, frame[4], frame[5]]))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--web", choices=["update", "check"])
    args = parser.parse_args()
    patches = records()
    names = [bytes(c if 32 <= c <= 126 else 32 for c in p[65:85]).decode().rstrip() for p in patches]
    lines = ["/* Generated from Sequential's unchanged v1.03 factory SysEx. */",
             "#pragma once",
             f"#define P5_FACTORY_N {len(patches)}u",
             "/* All 200 programs are engine factory presets. Native user slots start empty. */",
             f"static const p5_patch_t P5_FACTORY[{len(patches)}] = {{"]
    for p in patches:
        lines.append("    {{" + ",".join(map(str, p[:133])) + "}," + ",".join(map(str, p[133:])) + "},")
    lines.append("};")
    lines.append("#define P5_FACTORY_PRESETS(X) \\")
    lines += [f"    X({json.dumps(n)}) \\" for n in names]
    lines.append("")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines + [""]))
    if args.web:
        editor = ROOT / "web/editor.html"
        source = editor.read_text()
        block = BEGIN + "\n/* Sequential v1.03; generated by tools/gen_prophet_factory.py. */\nconst P5_FACTORY = " + json.dumps([list(p) for p in patches], separators=(",", ":")) + ";\n" + END
        start, end = source.index(BEGIN), source.index(END) + len(END)
        if args.web == "check":
            if source[start:end] != block:
                raise SystemExit("Prophet web defaults differ; regenerate with --web update")
        else:
            editor.write_text(source[:start] + block + source[end:])
    print(f"Prophet factory: {len(patches)} exact native programs -> {args.output}")


if __name__ == "__main__":
    main()
