#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Kerem Kilic (Ellic Studio)
"""Import data from an OB-Xf checkout (https://github.com/surge-synthesizer/OB-Xf, GPL-3.0-or-later) into the
OBXF engine. The outputs are checked in; run this again only to refresh them.

  tools/obxf_import.py blep <OB-Xf>/src/engine/BlepData.h > firmware/src/obxf_blep.h
  tools/obxf_import.py patches <OB-Xf>/assets/installer/"Surge Synth Team"/OB-Xf/Patches [LIST] \
      > firmware/src/eng_obxf_rom.h

blep: OB-Xf's blep and blamp tables (65 rows of 32: a 2049-entry polyphase table, row p sample i at 64 i + p,
symmetric about entry 1024) -> their first 1025 entries as float.

patches: the factory patches (.fxp: an XML chunk of normalized values; every one is CC0) named in LIST
(tools/obxf_patches.txt: "Category/File name = SHOWN NAME") -> the OBXF patch layout (eng_obxf.c OXF_PARAMS): a
continuous value as round(v * 16256), a switch or a choice as its value, read as OB-Xf's SynthEngine reads it,
and the presets (PTCH = the patch, the sends by category).
"""
import re
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ONE = 16256                      # 1.0 (127 << 7): a 7-bit step is exact, 0.5 too


def f32(x):
    return struct.unpack("f", struct.pack("f", x))[0]


def ffmt(x):
    s = "%.9g" % f32(x)                       # 9 digits: the float exactly
    if "e" not in s and "." not in s:
        s += ".0"
    return s + "f"


def blep(path):
    src = Path(path).read_text()
    out = ["/* SPDX-License-Identifier: GPL-3.0-only",
           " * Generated by tools/obxf_import.py from OB-Xf's src/engine/BlepData.h",
           " * (https://github.com/surge-synthesizer/OB-Xf, GPL-3.0-or-later; OB-Xd's tables by Vadim Filatov).",
           " * The first 1025 of the 2049 entries of each polyphase table (row p sample i = entry 64 i + p); the",
           " * rest mirror them (obxf_core.c oxf_tab). */"]
    for name, cname in (("blep", "OXF_BLEP"), ("blamp", "OXF_BLAMP")):
        m = re.search(r"const float %s\[\]\s*=\s*\{(.*?)\};" % name, src, re.S)
        vals = [float(v.rstrip("f")) for v in re.findall(r"[-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?f?", m.group(1))]
        if len(vals) != 65 * 32:
            raise SystemExit(f"{name}: {len(vals)} values, expected {65 * 32}")
        full = [None] * 2049
        for p in range(65):
            for i in range(32):
                k = 64 * i + p
                if k < 2049:
                    if full[k] is not None and full[k] != vals[p * 32 + i]:
                        raise SystemExit(f"{name}: rows disagree at entry {k}")
                    full[k] = vals[p * 32 + i]
        err = max(abs(full[k] - full[2048 - k]) for k in range(2049))
        if err > 1e-6:
            raise SystemExit(f"{name}: not symmetric ({err})")
        out.append(f"static const float {cname}[1025] = {{")
        half = full[:1025]
        for j in range(0, 1025, 6):
            out.append("    " + ", ".join(ffmt(v) for v in half[j:j + 6]) + ",")
        out.append("};")
    print("\n".join(out))


def layout():
    """eng_obxf.c's OXF_PARAMS (and OXF_LFO, twice): [(id, OB-Xf name, kind, lo, hi, init)] in patch order"""
    src = (HERE.parent / "firmware" / "src" / "eng_obxf.c").read_text()
    row = re.compile(r'X\(([\w#]+), (?:N )?"(\w+)", "[^"]*", ([CD]), \w+, (-?\d+), (-?\d+), ([^,]+), \w+\)')
    lfo = [m.groups() for m in row.finditer(src[src.index("#define OXF_LFO("):])]
    out = []
    for line in src[src.index("#define OXF_PARAMS("):src.index("#define OXF_LFO(")].splitlines():
        m = row.search(line)
        if m:
            out.append(m.groups())
            continue
        m = re.search(r'OXF_LFO\(X, (\w+), "(\w+)"\)', line)
        if m:
            out += [(m.group(1) + i[0][1:] if i[0].startswith("L") else i[0], m.group(2) + i[1], *i[2:])
                    for i in [("L" + g[0][3:], *g[1:]) for g in lfo]]
    return [(i, n, k, int(lo), int(hi), float(eval(init.replace("f", "")))) for i, n, k, lo, hi, init in out]


def jround(x):                    # juce::roundToInt / std::round: halves away from zero
    return int(x + 0.5) if x >= 0 else -int(-x + 0.5)


def to_value(pid, kind, lo, hi, x):
    """OB-Xf's normalized x -> the stored value (SynthEngine's process* conversions)"""
    if kind == "C":
        return max(0, min(ONE, jround(f32(x) * ONE)))
    if pid in ("NCOL",):
        v = 0 if x < 1 / 3 else 1 if x < 2 / 3 else 2
    elif pid == "XPM":
        v = jround(f32(x * 14))
    elif pid in ("LEG",):
        v = int(f32(f32(x) * 3))
    elif pid == "PRIO":
        v = int(f32(f32(x) * 2))
    elif pid == "TRNS":
        v = jround(f32((f32(x) * 2 - 1) * 24))
    elif pid in ("UNIV", "POLY"):
        v = min(32, 1 + int(f32(f32(x) * 32)))
    elif re.match(r"L[12](P1|P2|CUT|PW1|PW2|VOL)$", pid):
        xr = jround(x * 2) * 0.5
        v = {0: 0, 1: 1, -1: 2}[jround(5 * xr - 6 * xr * xr)]
    elif pid == "HQ":
        v = int(x > 0.5)
    else:                         # a switch (FOUR: the 4-pole mode)
        v = int(x >= 0.5)
    return max(lo, min(hi, v)) - lo


CAT_FX = {"Basses": (0, 0, 10, 10, 2), "Brass": (0, 20, 20, 40, 6), "Keys": (0, 30, 25, 35, 6),
          "Leads": (10, 20, 40, 30, 4), "Pads": (0, 40, 30, 70, 5), "Strings": (0, 40, 25, 60, 5),
          "Organs": (10, 40, 0, 30, 6), "Plucks": (0, 20, 35, 30, 3), "Mallets": (0, 0, 25, 40, 3),
          "Bells": (0, 10, 30, 70, 7), "Voices": (0, 40, 30, 70, 5), "Winds": (0, 20, 30, 50, 4),
          "FX": (0, 0, 40, 50, 0), "Atmospheres": (0, 30, 40, 70, 5), "Drums": (0, 0, 10, 20, 12),
          "Percussion": (0, 0, 15, 30, 12), "Guitars": (0, 20, 25, 30, 3), "Soundscapes": (0, 30, 40, 70, 5)}


def patches(folder, listfile):
    lay = layout()
    if len(lay) != 95:
        raise SystemExit(f"layout: {len(lay)} parameters, expected 95")
    rows, presets, names = [], [], []
    for line in Path(listfile).read_text().splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        rel, shown = (x.strip() for x in line.split("="))
        if len(shown) > 12 or not re.fullmatch(r"[A-Z0-9 .&'+-]+", shown):
            raise SystemExit(f"{shown!r}: at most 12 of A-Z 0-9 space . & ' + -")
        data = (Path(folder) / (rel + ".fxp")).read_bytes().decode("latin1")
        attrs = dict(re.findall(r' (\w+)="([^"]*)"', data[data.index("<OB-Xf"):]))
        if not attrs.get("license", "").startswith("CC0"):
            raise SystemExit(f"{rel}: not CC0")
        vals = []
        for pid, xml, kind, lo, hi, init in lay:
            if xml in attrs:
                vals.append(to_value(pid, kind, lo, hi, float(attrs[xml])))
            else:                 # not in the file: OB-Xf's default
                vals.append(jround(init * ONE) if kind == "C" else int(init) - lo)
        cat = rel.split("/")[0]
        rows.append((shown, vals, rel, attrs.get("author", "?")))
        d, c, dl, r, pat = CAT_FX.get(cat, (0, 20, 25, 40, 0))
        presets.append(f'    OXF_PR("{shown}", {len(rows) - 1}, FX({d}, {c}, {dl}, {r}), PAT({pat})),')
        names.append(f'"{shown}"')
    out = ["/* SPDX-License-Identifier: GPL-3.0-only",
           " * Generated by tools/obxf_import.py from OB-Xf's factory patches (https://github.com/surge-synthesizer/OB-Xf;",
           " * every patch here is marked CC0 / public domain by its author, named in its comment) and",
           " * tools/obxf_patches.txt. The layout is eng_obxf.c OXF_PARAMS. */",
           f"#define OXF_NROM {len(rows)}u",
           "static const oxf_rom_t OXF_ROM[OXF_NROM] = {"]
    for shown, vals, rel, author in rows:
        out.append(f'    {{"{shown}", {{{", ".join(map(str, vals))}}}}},   /* {rel}, {author} */')
    out.append("};")
    out.append("static const char *const N_OXF_PATCH[OXF_NROM + 1] = {")
    for j in range(0, len(names), 6):
        out.append("    " + ", ".join(names[j:j + 6]) + ",")
    out.append("    0};")
    out.append("#define OXF_PR(name, ptch, fx, pat) {name, {0, 0, 0, 0, 0, 0, 0, ptch}, {0, 0, 127, 0}, 0, 0, fx, pat}")
    out.append("static const preset_t OBXF_PRESETS[OXF_NROM] = {")
    out += presets
    out.append("};")
    out.append("#undef OXF_PR")
    print("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "blep":
        blep(sys.argv[2])
    elif len(sys.argv) >= 3 and sys.argv[1] == "patches":
        patches(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else str(HERE / "obxf_patches.txt"))
    else:
        raise SystemExit(__doc__)
